### ISSUE TITLE
Plugin Not finding size of site; stops backups from running

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1084] opened 2016-07-22 15:12 UTC
We have had several complaints of backups not running. In almost all cases I could link to this issue, the backup acts like it will complete, the page reloads, but no backup ever completes when "Run Now" is pressed. No schedules complete.  

This was first seen about 2 months ago. I had originally added an issue and at that point we thought it was something to do with file handling and plugin not being able to read all the different files on the site, but I can't find that "issue" anymore. So I am re-doing the issue with hopefully more helpful info. 

When I investigate I find the information from the support module shows the following: 

- All needed functions are usually installed; 
- No apparent wp-cron or other conflicts; 
- Sites are of all sizes - includes some very large and some very small (when info is available);
- No specific correlation to any plugin found after testing; 
- The only consistent thing found in all of these is that the "Calculate Size of Site" isn't find the size of the site.  (see image below) 

<img width="254" alt="screen shot 2016-07-22 at 10 29 37 am" src="https://cloud.githubusercontent.com/assets/5481211/17060829/ced448ba-4ff9-11e6-8a61-5d61eccc6734.png">

I haven't yet found any accompanying errors or other things I can point to as an obvious cause for this. The best I can point to is that it seemed to begin after an update a couple months back.

**Comment by pdewouters** [comment] 2016-07-22 17:04
when you visit excludes, are there file sizes? or just spinners? might be because the transient that contains the file list is too big

**Comment by katmoody** [comment] 2016-08-23 16:20
Finally got in on a site that is having this specific issue @pdewouters and it does just spin - only on the folders, not the individual files. Even if I click through one of the directories - the folders will spin but the individual files don't. 

here's a screenshot: 
![screenshot](https://cloud.githubusercontent.com/assets/5481211/17900121/f60578aa-692b-11e6-84a8-200be039f48e.png)

Do you need to know anything else specifically? This site has access in Intercom if you'd like to look further!

**Comment by willmot** [comment] 2016-08-26 13:12
Closing as a dupe of https://github.com/humanmade/backupwordpress/issues/1063

**Comment by willmot** [comment] 2016-08-26 16:42
Oops, this wasn't a dupe

**Comment by willmot** [comment] 2016-08-26 17:14
> when you visit excludes, are there file sizes? or just spinners? might be because the transient that contains the file list is too big

Filesizes aren't stored in a transient, they are stored in a file which is auto-excluded.

> Plugin Not finding size of site; stops backups from running

This is two separate issues, the site size calculation is likely timing out before it can complete. Similarly, file backups are also likely timing out before they can complete. However the later isn't caused by the former. There isn't a "bug" in site size calculations that is breaking backups. It's just that both issues are likely to happen on hosts with low servers limits.

We have an issue open to cover making the site size calculation more resilient to timeout errors: https://github.com/humanmade/backupwordpress/issues/752

backup timeouts are a harder problem, although https://github.com/humanmade/backupwordpress/pull/1025 is a step in the direction.

Closing this issue as it isn't a new problem, just two existing problems happening together.

**Closed by willmot** 2016-08-26 17:14 UTC
