### ISSUE TITLE
Site Root Path Unreadable

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#976] opened 2016-01-27 14:16 UTC
Users are getting a Site Root path unreadable error when they try to scan their site. 
ex. from forums: https://wordpress.org/support/topic/your-site-root-path-isnt-readable?replies=6

Might be related to #975

**Comment by pdewouters** [comment] 2016-01-27 15:53
This should be fixed by upgrading to 3.4.2

**Comment by willmot** [comment] 2016-02-01 15:57
@pdewouters don't think this is fixed by 3.4.2, should be fixed by https://github.com/humanmade/backupwordpress/pull/977 though

**Comment by pdewouters** [comment] 2016-02-01 16:10
@willmot oh, I say that because on my local install I reproduced the error message, being on a 3.4.1 install and as soon as I updated the plugin, the message disappeared

**Comment by willmot** [comment] 2016-02-01 16:12
Oh hmm, wonder what we changed that fixed that. Looking at https://wordpress.org/support/topic/your-site-root-path-isnt-readable?replies=6 it seems others reported it fixed too. Closing.

**Comment by katmoody** [comment] 2016-02-03 14:28
Receiving new tickets regarding this today, after updating to 4.3.2 - have logins for troubleshooting but not sure what to troubleshoot myself?

**Comment by katmoody** [comment] 2016-02-03 14:46
![tools php](https://cloud.githubusercontent.com/assets/5481211/12785492/c29be794-ca5a-11e5-956a-d7b2204d2e37.jpg)
As you can see, in this case the error displays but nothing else loads on the admin page beyond that. 

This is happening on two sites so far within Intercom and both have offered login credentials - I'm just not sure what to check: 

https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1847295244
and 
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1849907120

**Comment by pdewouters** [comment] 2016-02-03 15:47
@katmoody I suggest first checking the Intercom data, Looking at this site, it looks like a weird server software is installed. I think we should make it clear that we only support Windows IIS and Apache/nginx on linux

<img width="243" alt="screenshot 2016-02-03 15 45 52" src="https://cloud.githubusercontent.com/assets/30460/12787439/599ab3be-ca8d-11e5-9e22-5159deeb7bd1.png">
<img width="196" alt="screenshot 2016-02-03 15 45 36" src="https://cloud.githubusercontent.com/assets/30460/12787441/599f43c0-ca8d-11e5-941c-1cdd7a19bceb.png">
<img width="336" alt="screenshot 2016-02-03 15 45 15" src="https://cloud.githubusercontent.com/assets/30460/12787440/599ec602-ca8d-11e5-8eff-706bf1b59bfd.png">

**Comment by willmot** [comment] 2016-02-03 15:50
There definitely seems to be something buggy going on here. I'll need FTP access to be able to debug any further.

**Comment by pdewouters** [comment] 2016-02-03 15:51
@willmot apparently $is_apache does not work for IdeaWebServer? https://core.trac.wordpress.org/ticket/9763

**Comment by willmot** [comment] 2016-02-03 15:55
Ah that's interesting, yeah perhaps we should just tell them that we don't support that web-server but that we'd be happy to work with them to add support if they want.

**Comment by katmoody** [comment] 2016-02-03 21:04
This ticket is not on one of the weird servers: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1849907120

**Comment by katmoody** [comment] 2016-02-03 21:08
This is another ticket, but he runs a lot of sites in a shared hosting environment (160) ... he ALSO has the zip error displaying as well. One other thing of note - he's on a Polish server - not sure if that matters or not :D 

https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1853589385

**Comment by pdewouters** [comment] 2016-02-04 09:24
Seems that the update I did broke it for other subdirectory configs :/

<img width="549" alt="screenshot 2016-02-04 09 23 36" src="https://cloud.githubusercontent.com/assets/30460/12810905/0cd5d65a-cb21-11e5-945b-39b1aabd33a3.png">

**Comment by pdewouters** [comment] 2016-02-04 09:35
<img width="819" alt="screenshot 2016-02-04 09 34 39" src="https://cloud.githubusercontent.com/assets/30460/12811166/90acc06e-cb22-11e5-8dd2-ceb3b290fe5d.png">

**Comment by pdewouters** [comment] 2016-02-04 09:44
I think maybe if there is an index.php a level up from a subdirectory install, it thinks that's the WP install root. Before we checked for both index.php and wp-config to determine if it was a subdir install. What other checks can we do?

**Comment by pdewouters** [comment] 2016-02-04 09:53
Could we detect if home_url has a subfolder in it? using explode or something

**Comment by pdewouters** [comment] 2016-02-04 10:10
@willmot I think a simple fix would be to check home_url vs site_url, unless you think that the scenario where multiple domains can point to the same install is more frequent that having the same URL but one with a subfolder in it ( which I don't). Otherwise, how can we reliably account for all scenarios?

**Comment by pdewouters** [comment] 2016-02-04 10:29
I suppose this is the case you meant in your PR comment? https://my.bluehost.com/cgi/help/wordpress_url#to_url

where one of the settings would be the temp URL and the other would be the final domain?

**Comment by willmot** [comment] 2016-02-04 10:56
> @willmot I think a simple fix would be to check `home_url` vs `site_url`

Multisite subdirectory installs break that unfortunately as they have both set to the base domain (see https://github.com/humanmade/backupwordpress/issues/695 & https://github.com/humanmade/backupwordpress/pull/260 for some background).

so I guess this would happen if someone has WordPress installed in a directory that itself is in another WordPress install, e.g.

```
index.php // a WordPress install
wp-content...
test // Another WordPress install
--- index.php
--- wp-config.php
```

In that case I think we can just check for the existence of an `index.php` outside root and assume it's not a subdirectory install if it exists. PR incoming.

**Comment by pdewouters** [comment] 2016-02-04 11:04
we can't assume `index.php` at the root belongs to WordPress though

**Comment by willmot** [comment] 2016-02-04 11:05
No but we can assume that if there is and index.php and a wp-config.php in the subdirectory then it's not a subdirectory install, it's just WordPress installed in a folder.

**Comment by willmot** [comment] 2016-02-04 11:22
Hopefully resolved in https://github.com/humanmade/backupwordpress/pull/983

**Comment by pdewouters** [comment] 2016-02-04 11:24
@willmot I don't think so: `Copy (NOT MOVE!) the index.php and .htaccess files from the WordPress directory`
this means a subdir install can have a wp-config and an index,php

**Comment by willmot** [comment] 2016-02-04 12:02
@pdewouters where are you quoting that from? Interesting though and definitely complicates things.

So that would mean that in the following setup:

```
index.php
wp-config.php
foo/
- index.php
- wp-config.php
```

That could either be a Subdirectory WordPress install in root or a standard install in `foo/`.

One way of detecting that would be to check `site_url` that would include `foo/` if it's a subdirectory install. Unfortunately in Multisite that's not the case.

**Comment by pdewouters** [comment] 2016-02-04 12:32
it's from the https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory

**Comment by willmot** [comment] 2016-02-04 12:36
So I still think it's safer to assume the install is `foo/` in that case as that was the behaviour we had previously.

**Comment by pdewouters** [comment] 2016-02-04 12:53
can we use `is_multisite()` in the check somehow?

**Comment by willmot** [comment] 2016-02-04 14:14
We could then at least solve it for single sites but the issue would still remain for `multisite` installs

**Comment by pdewouters** [comment] 2016-02-05 10:42
@katmoody as a temporary fix, can you tell users to define `HMBKP_ROOT` in their `wp-config.php` file to the correct absolute path to their WordPres install.
Should look something like `define( 'HMBKP_ROOT', '/path/to/wordpress' );`
could we not just add a text field to the admin UI : "We detected this path to be the root of your WordPress installation, please confirm or amend if necessary".

**Comment by pdewouters** [comment] 2016-02-05 10:51
Also, still on the Codex page , it says 
> As of Version 3.5, Multisite users may use all of the functionality listed below. If you are running a version of WordPress older than 3.5, please update before installing a Multisite WordPress install on a subdirectory.

So this would mean that `site_url` and `home_url` will be different for multisite too

**Comment by pdewouters** [comment] 2016-02-05 11:04
Or can't we just rely on the core `get_home_path()` function?

**Comment by pdewouters** [comment] 2016-02-05 11:52
Anyway, I think I need to create a test environment with all possibilities. So I'll set up a local site with:

root: standard WP install
subfolder with a WP install
subfolder with a multisite

another site with a subfolder install as described in codex

Any other cases?

**Comment by pdewouters** [comment] 2016-02-05 14:56
The issue that needs fixing is when a user has a WP install in a subfolder of his hosting filesystem, not WP in a subdirectory necessarily.
In the first case, the root path will still be the root of the filesystem instead of the root of the WP install subfolder and will therefore backup the entire hosting filesytem.
In my tests, using the core `get_home_path()` fixes the issue.

I haven't figured out how to install WP in a subdirectory on Windows with web matrix yet though

**Comment by katmoody** [comment] 2016-02-05 15:16
@pdewouters would this also solve the issue of not being able to only backup the files within the actual site when the site is in a subdirectory? I've gotten at least two tickets with this specific concern - all the root directory sites/folders are viewable and have to be excluded, but in some cases they can't be excluded.

**Comment by pdewouters** [comment] 2016-02-05 15:40
ah but that function isn't available for cron jobs

**Comment by katmoody** [comment] 2016-02-26 15:33
According to those in forums (still awaiting contact in Intercom) this is still not resolved for everyone so I'm reopening this.

**Comment by willmot** [comment] 2016-02-26 15:49
@katmoody could you drop a link to the forums thread where this is reported as not fixed

**Comment by katmoody** [comment] 2016-02-26 15:50
Here you go: https://wordpress.org/support/topic/your-site-root-path-isnt-readable?replies=24#post-8082492

**Comment by willmot** [comment] 2016-02-29 22:51
@katmoody has anyone contacted support with a reproducible issue here? I'm tempted to close this out until such a time as we have a verifiable issue.

**Comment by katmoody** [comment] 2016-03-01 14:15
Nothing reproducible yet here. I also am wondering if the plugin is more accurately letting people know they even have the error, where before they might have had failed backups without a warning? I wonder because for the last three people I checked with, having them set the root path in the wp-config worked to fix the problem. Thoughts?

**Comment by willmot** [comment] 2016-03-01 15:18
@katmoody so there was actually an issue for folks on Windows servers, I found and fixed that this morning (see https://github.com/humanmade/backupwordpress/issues/1012), my guess is that the folks who've reported the issue were on Windows.

Let's close this and if / when it comes back we can re-open and tackle whatever edge-case.

**Closed by willmot** 2016-03-01 15:18 UTC
Labels: Bug
