### ISSUE TITLE
IIS: Unexpected Value Exception 

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#738] opened 2015-02-17 15:33 UTC
![screen 20shot 202015-02-17 20at 2013 06 36](https://cloud.githubusercontent.com/assets/1263370/6230723/df4f270a-b68f-11e4-870a-7e2f10668be7.png)

I found this:
http://stackoverflow.com/questions/4547485/can-i-make-recursivedirectoryiterator-skip-unreadable-directories

I will try to reproduce later today an update this ticket.

**Comment by owaincuvelier** [comment] 2015-02-18 16:45
I think a related issue. 

![screen shot 2015-02-18 at 11 44 35](https://cloud.githubusercontent.com/assets/1263370/6251729/90b972b0-b763-11e4-8622-674fdd7211fe.png)

**Comment by owaincuvelier** [comment] 2015-02-27 16:58
So far in my efforts to debug the issue BackUpWordPress has been able to detect files as unreadable/inaccessible.

**Comment by owaincuvelier** [comment] 2015-02-27 17:13
@pdewouters maybe this is related? https://bugs.php.net/bug.php?id=43817

**Comment by pdewouters** [comment] 2015-02-27 17:28
Good research! I think I know the fix

**Comment by owaincuvelier** [comment] 2015-08-27 09:41
IIS still throws the fatal.

`
Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(D:/Hosting/10249822/html,D:/Hosting/10249822/html) [<a href='recursivedirectoryiterator.--construct'>recursivedirectoryiterator.--construct</a>]: Access is denied. (code: 5)' in D:\Hosting\10249822\html\wp-content\plugins\backupwordpress\vendor\symfony\finder\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator.php:49 Stack trace: #0 D:\Hosting\10249822\html\wp-content\plugins\backupwordpress\vendor\symfony\finder\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator.php(49): RecursiveDirectoryIterator->__construct('D:/Hosting/1024...', 4608) #1 D:\Hosting\10249822\html\wp-content\plugins\backupwordpress\vendor\symfony\finder\Symfony\Component\Finder\Adapter\PhpAdapter.php(35): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->__construct('D:/Hosting/1024...', 4608, true) #2 D:\Hosting\10249822\html\wp-content\plugins\backupwordpress\vendor\symfony\finder\Symfony\Component\Finder\Find in D:\Hosting\10249822\html\wp-content\plugins\backupwordpress\vendor\symfony\finder\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator.php on line 49
`

**Comment by willmot** [comment] 2016-01-24 00:08
Pretty sure this was resolved by #936, I'm certainly not able to reproduce on my IIS copy.

Closing, we can re-open if this shows up again.

**Closed by willmot** 2016-01-24 00:08 UTC
Labels: Bug
