### ISSUE TITLE
Better error handling when mysqldump and pdo_mysql are both missing

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#959] opened 2016-01-07 14:54 UTC
So far, I've gotten a few tickets (and in the forums) in which the update to include MySQLDump actually makes the plugin fail, and it looks like that is because the fallback method isn't working for some reason? 

Examples of tickets: 
Intercom: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1674279260
wp.org forum: https://wordpress.org/support/topic/mysqldump_fallback

**Comment by willmot** [comment] 2016-01-07 15:18
@katmoody would be good to test whether the 3.4-alpha resolves this.

**Comment by willmot** [comment] 2016-01-19 13:53
@katmoody could you confirm if https://github.com/humanmade/backupwordpress/releases/tag/3.4-rc1 fixes this.

**Comment by willmot** [comment] 2016-01-22 15:13
@katmoody I actually don't think this will be resolved by 3.4.1. The issue is that his host doesn't have mysql PDO which is required for mysqldump fallback.

It's strange as Intercom reports that he does have mysql, perhaps it's just incorrectly installed...

<img width="357" alt="screen shot 2016-01-22 at 15 13 03" src="https://cloud.githubusercontent.com/assets/308507/12514303/a5e1de72-c11a-11e5-82ba-54fc10ba983e.png">

He'll need to get his host to install mysql PDO.

But we should be catching this error more nicely, I'll update this ticket to reflect that.

**Comment by willmot** [comment] 2016-01-22 15:16
This is the specific PHP error that we hit

```
PHP Fatal error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /kunder/wp/c/ceeview/wp/wp-content/plugins/backupwordpress/vendor/ifsnop/mysqldump-php/src/Ifsnop/Mysqldump/Mysqldump.php on line 147
```

**Comment by willmot** [comment] 2016-01-23 23:41
I added support for catching this error and showing a nice message. However this doesn't really fix the issue as users without access to `mysqldump` or `PDO` won't be able to back up their database.

One potential solution would be to bring back the old PHP fallback which imysqldump replaced, similar to have we're thinking of bringing pclzip back. I've opened https://github.com/humanmade/backupwordpress/issues/969 to track that.

**Closed** 2016-01-25 09:46 UTC
Labels: Bug

**Comment by katmoody** [comment] 2016-01-25 15:14
One person who had this issue just reported back, @willmot - they said that everything is working fine now -  after their provider recompiled PHP for the given server. 

What does this mean? Is it something I can recommend to others with the same issue?

**Comment by willmot** [comment] 2016-01-25 15:22
> they said that everything is working fine now - after their provider recompiled PHP for the given server.

So we have two different ways of backing up the database. The best way is to use `mysqldump` which requires `shell_exec` to be working and `mysqldump` to be installed on the server and accessible. If that way isn't possible then we fallback to using a PHP only method which relies on PHP being compiled with PDO support (which it nearly always is).

Users who's servers don't have either of those things won't be able to perform database backups. The only way for them to fix that is for them to update their server to support either `mysqldump` or `PDO`.

The only thing we can improve in the plugin with regards to this is to show a better error message.

**Comment by MarZab** [comment] 2016-07-30 11:00
I had the same error `Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY'` with a silent fail. Frontend looked like it was all working just really long. Did not have PDO support :)

A better error message would be really good.
