### ISSUE TITLE
Display whether backup results from manual or scheduled backup

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#760] opened 2015-03-12 13:52 UTC
It would be useful to display whether a backup was triggered by a schedule or manually ran.

**Comment by willmot** [comment] 2015-03-14 17:06
Yeah I like this idea. Although there's no way to detect this currently. We'd either need to start storing information about each backup in the database or store `manual` / `automatic` as part of the backup filename string.

**Comment by willmot** [comment] 2015-07-20 19:00
Closing as a duplicate of #403

**Closed by willmot** 2015-07-20 19:00 UTC
