### ISSUE TITLE
Process error with Zip

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1046] opened 2016-03-28 14:42 UTC
`Zip: The process has been signaled with signal "15"`
The backup size won't complete (just spins) and the backups don't work. 

Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/2001101400

**Comment by willmot** [comment] 2016-03-31 09:42
That means something is killing the backup process, will be helped by 3.6 and https://github.com/humanmade/backupwordpress/pull/1025

**Comment by willmot** [comment] 2016-04-01 13:37
Closing as a dupe of https://github.com/humanmade/backupwordpress/pull/1025

**Closed by willmot** 2016-04-01 13:37 UTC
Labels: Bug
