### ISSUE TITLE
ZipArchive::close Error with failed backup

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1044] opened 2016-03-28 14:03 UTC
`php: ZipArchive::close(): Renaming temporary file failed: No such file or directory, /home/aacnwiki/public_html/theabcn.org/wp-content/plugins/backupwordpress/classes/backup/class-backup-engine-file-zip-archive.php, 47`

I'm unsure if this is similar to the error reported in #1017 but it's resulting in the same issue - it keeps backups from running. If it is similar to the other, then bringing back PCLZip might be best counter. But is it that or is it trying to find files that it's not able to access for some reason? Not positive about either?

Intercom ticket: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/4415126144

**Comment by willmot** [comment] 2016-03-31 09:44
Yeah this is a dupe of https://github.com/humanmade/backupwordpress/issues/1017

**Closed by willmot** 2016-03-31 09:44 UTC
Labels: Bug
