### ISSUE TITLE
If backup is cancelled during upload to remote destination do not delete finished backup

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#810] opened 2015-04-27 17:13 UTC
Also:
> Hi, thanks for the awesome plugin guys! However, I'm experiencing an issue with it. Backup stucks at 'Creating zip archive' step. However, I can see that the actual zip backup file is created in the appropriate backup folder on the server. Moreover, it is valid and opens alright. But as soon as I click 'cancel' right near 'Creating zip archive', the plugin deletes this backup archive from the folder. It looks like there is some issue with the script execution. Max_execution_time = 1600 so no trouble here. Because of this issue, backup is not happening according to schedule. Please help. Thank you.

**Comment by willmot** [comment] 2015-07-17 15:50
It would be good to dig into why the backup isn't getting marked as complete.

I'm not sure we'll be able to reliably tell whether a backup is complete but incorrectly marked as finished (and thus we shouldn't delete) vs the backup has been cancelled and should be deleted.

**Comment by pdewouters** [comment] 2015-07-18 13:17
I think it does get to the backup complete step, but `creating zip archive` is the last status displayed to the user.

**Comment by willmot** [comment] 2015-07-18 13:22
The final backup step `hmbkp_complete` should then delete the `.backup_running` file and thus clear the status.

Maybe it's just that something is interrupting the ajax request which updates that status and a thus a page refresh would then show the backup as done?

**Comment by pdewouters** [comment] 2015-10-11 09:35
Well, if we get to `hmbkp_backup_complete` we can assume it was done successfully.

**Comment by pdewouters** [comment] 2015-10-11 10:30
The issue is when there is an unexpected / uncaught error in an function that hooks into `hmbkp_backup_complete`, the BackUp errors are not populated and the process just hangs.

**Comment by willmot** [comment] 2015-11-30 00:39
@pdewouters having had a look at the extensions I think the issue is that you're calling `$backup->error` if there's an error when in-fact you should be calling `$backup->warning`. `backup->error` causes the backup to be deleted.

**Comment by willmot** [comment] 2016-01-19 13:57
We need to fix this on the extension side not in BackUpWordPress. I'll leave this open until we've at least created issues on the extension repos though.

**Comment by willmot** [comment] 2016-02-29 22:58
This is fixed by #1007

**Closed by willmot** 2016-02-29 22:58 UTC
Labels: Bug, Reporter Feedback
