### ISSUE TITLE
Suppress errors

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#747] opened 2015-03-03 14:45 UTC
There are a couple of errors that might be worth hiding. They can cause confusion to users and also give a false impression of why their backups are failing.

```
sh: /usr/bin/zip: Permission denied
HMBKP_SUCCESSsh: /usr/bin/zip: Permission denied
HMBKP_SUCCESS
```

**Comment by pdewouters** [comment] 2015-03-03 15:19
I thought I fixed the dropbox one

**Comment by owaincuvelier** [comment] 2015-03-03 15:26
yeah you did! Forgot to clear it from my Trello!

**Comment by willmot** [comment] 2015-03-14 17:22
The `zip` error is caused when it tries to add a file that it doesn't have read access to. It's not easy to avoid as we don't know which files are going to be unreadable and it would be expensive to scan the whole site prior to calling `zip` just so we could exclude unreadable files.

Given unreadable files are marked as such in the excludes site file browser, we could just catch and suppress that specific message.

**Comment by pdewouters** [comment] 2015-04-14 09:28
I can't reproduce this, I have a folder with no permissions and it does not cause an error:
`d--------- 1 vagrant vagrant    68 Feb 18  2014 __private`

**Comment by owaincuvelier** [comment] 2015-04-14 09:36
I think this error is when the unix zip command is installed on the server but the users doesn't have permission to use it. It's not a folder permission.

**Comment by willmot** [comment] 2015-04-14 11:10
The error is caused when you try to zip up a file you don't have read access to

Here's what I did to prove it

Here's how you zip up a file
```
$ zip foo.zip IMG_0833.jpg 
  adding: IMG_0833.jpg (deflated 0%)
```

Let's get rid of it

```
$ rm foo.zip 
```

And then remove our read permission from the file

```
$ sudo chmod 000 IMG_0833.jpg 
```

Then try to zip up again, I'm using `-q` for quiet output as that's what we do in BWP

```
$ zip foo.zip -q IMG_0833.jpg 
zip warning: Permission denied
```

Here's what you get if you ommit `-q`

```
$ zip foo.zip IMG_0833.jpg 
  adding: IMG_0833.jpg
zip warning: Permission denied
	zip warning: could not open for reading: IMG_0833.jpg

zip warning: Not all files were readable
```

If we removed `-q` we could perhaps parse out the list of unreadable files and use them to show a better error message. That likely would be easy though as we intentionally silence output so that we can treat any output as an error.

**Comment by pdewouters** [comment] 2015-04-14 11:35
ah, I see. I chmodded a file to 000 but for some reason it still had read permissions

**Comment by willmot** [comment] 2015-07-20 18:05
Closing this in favour of #529

**Closed by willmot** 2015-07-20 18:05 UTC
Labels: Enhancement
