### ISSUE TITLE
Allow multiple file exclusions at one time

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1066] opened 2016-04-28 14:45 UTC
Easier handling of multiple exclusions would be a big enhancement. Though it's partially addressed by tickets like #905 having checkmarks for selecting multiple options at once, or some other method would be beneficial. 

I thought this was already listed somewhere but didn't see it. It's a frequently requested item for enhancement. :D

**Comment by willmot** [comment] 2016-04-28 14:54
Can you think of any other methods other than checkmarks?

**Comment by katmoody** [comment] 2016-04-28 14:56
Just selecting them all at once as we currently select them, without the Ajax request until the "Done" button is clicked? (That is an Ajax request to refresh every time something is clicked, right?)

**Comment by willmot** [comment] 2016-08-28 23:40
Closing as a dupe of https://github.com/humanmade/backupwordpress/issues/532

**Closed by willmot** 2016-08-28 23:40 UTC
Labels: Enhancement
