### ISSUE TITLE
Excluded Directory removal causes Backup Error

### ISSUE THREAD

**Issue by DavidDwier** [humanmade/backupwordpress#665] opened 2015-01-04 01:41 UTC
This is not a real issue, but something which could be improved:
The following scenario causes a "Complete Weekly" Backup to fail:
Exclude a directory in the "Complete Weekly" Exclude-Settings.
Delete this directory manually from the server using a ftp-client.
The Backup will fail with a 500 error.

Solution: Remove the Folder from the Exclusion List or create the folder via ftp.

**Comment by willmot** [comment] 2015-01-04 09:47
Thanks for the report, agree that definitely shouldn't happen, will do some testing and fix.

**Comment by owaincuvelier** [comment] 2015-01-20 11:48
I've been unable to reproduce this error as yet.

**Comment by willmot** [comment] 2015-01-21 07:51
Yeah I haven't been able to reproduce either

**Comment by owaincuvelier** [comment] 2015-03-11 12:04
Closing out as we haven't had any other reports and been unable to reproduce.

**Closed by owaincuvelier** 2015-03-11 12:04 UTC
