### ISSUE TITLE
Backup Doesn't Run, stuck on "Deleting Old Backups" message

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#1039] opened 2016-03-17 15:53 UTC
I've seen this on a couple sites, and though I am waiting further feedback I wanted to list it for feedback. Instead of the backup running, the message at the top says it is deleted old backups. Then the page refreshes with no saved backup. Same with database or complete backups. 

![backups](https://cloud.githubusercontent.com/assets/5481211/13852040/d49fd128-ec36-11e5-8b84-3bc84e7b191b.jpg)

**Comment by willmot** [comment] 2016-04-01 13:36
This will be resolved by https://github.com/humanmade/backupwordpress/pull/1025 so I'm going to close as a dupe of that.

**Closed by willmot** 2016-04-01 13:36 UTC
Labels: Bug
