### ISSUE TITLE
Site size isn't refreshed when adding a new file

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#677] opened 2015-01-09 17:30 UTC
I added a large video file to my local dev site, but it is not getting indexed.

**Comment by willmot** [comment] 2015-01-09 21:47
The site size is auto refreshed once per week, you can force a refresh by clicking excludes, hovering over a directory size and clicking the refresh icon. (We should maybe add the same click to refresh functionality to the main site size shown in the schedule sentence.

**Comment by willmot** [comment] 2015-07-20 18:38
Closing as a duplicate of #784

**Closed by willmot** 2015-07-20 18:38 UTC
Labels: Bug
