### ISSUE TITLE
Don't display entire 404 errors/notices

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress#669] opened 2015-01-06 12:48 UTC
There seems to be an issue with error reporting. This is a typical error message.

@pdewouters I've not been able to reproduce it locally as yet.

![screencapture-memory-foundation-wp-admin-tools-php](https://cloud.githubusercontent.com/assets/1263370/5628642/0e0a671c-95a2-11e4-9e64-7f4eae4ca08e.png)

**Comment by pdewouters** [comment] 2015-01-06 15:22
We should just show a generic message for this type of error. There is probably an Ajax error that returns a 404.

**Comment by willmot** [comment] 2015-01-06 17:30
Would be good to look into why a `404` is being returned as that really shouldn't be possible.

If you try to visit `/wp-cron.php` on that site do you get a `404`?

**Comment by owaincuvelier** [comment] 2015-01-06 17:35
Just getting a white screen when going to ```/wp-cron.php```.

**Comment by willmot** [comment] 2015-01-06 17:37
> Just getting a white screen when going to /wp-cron.php.

That's expected, really you want to check what `headers` are returned, in terminal you can do `curl -I google.com` to get the header for a url.

**Comment by owaincuvelier** [comment] 2015-01-06 17:40
>HTTP/1.1 200 OK
>Date: Tue, 06 Jan 2015 17:38:44 GMT
>Server: Apache
>Expires: Thu, 19 Nov 1981 08:52:00 GMT
>Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
>Pragma: no-cache
>Set-Cookie: PHPSESSID=wBPG9ERhbEi1UCpLEMZSa3; path=/
>Vary: Accept-Encoding
>Content-Type: text/html

**Comment by willmot** [comment] 2015-01-06 17:44
Yeah that's what's so strange, that's returning a `200` response, not a `404` error.

It would be good to get access to their server and run a `wp_remote_head( site_url( 'wp-cron.php' ) )` and see whether that gives a 404.

It may be a genuine bug that we are showing 404's here.

**Comment by willmot** [comment] 2015-01-26 12:23
We'll cover this off in #608

**Comment by willmot** [comment] 2015-07-20 18:39
Closing as a dupe of #608

**Closed by willmot** 2015-07-20 18:39 UTC
Labels: Bug
