### ISSUE TITLE
Incomplete Database

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#979] opened 2016-01-27 17:00 UTC
Database backups completed but only showing a partial backup. 

See ticket on wp.org: https://wordpress.org/support/topic/empty-database-dump-after-update?replies=1
See ticket on Intercom: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1766861518

**Comment by katmoody** [comment] 2016-02-01 14:53
Interesting coincidence(?) noted in the forums on this same issue affected sites are all using PHP 5.4.39 and sites using other versions are unaffected by this one ... could PHP version impact this in some way? https://wordpress.org/support/topic/empty-database-dump-after-update?replies=9#post-7968190

**Comment by willmot** [comment] 2016-02-01 15:55
It would be pretty odd for this to be a PHP specific reason, worth checking though as we need to reproduce before we can track down a fix.

**Comment by willmot** [comment] 2016-02-01 15:55
Do we have access to anyones site / server where this is happening?

**Comment by katmoody** [comment] 2016-02-01 15:57
I'll ask if the one doing so much troubleshooting would be willing to assist in this way :D He's been the most proactive of the bunch.

**Comment by RubenMartins** [comment] 2016-02-11 16:54
Hello, This is also happening with me in 5.3.29 php version
Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4 PHP/5.3.29

On the version 3.4.2 of the plugin this works fine on the same enviroment, just after update to the latest version of 3.4.3 the database was truncated since then on the database backup and also on the complete backup.

What more information do you need to try to reproduce the error?

I saw that the latest version fix a bug where backups were not downloadable when WordPress installed in a subdirectory could the some changed here?

**Comment by pdewouters** [comment] 2016-02-11 17:25
@RubenMartins thanks for the report. if you revert to the previous version , does it still happen or does it do a complete backup. there wasn't any change related to db backup between 3.4.2 and 3.4.3

**Comment by RubenMartins** [comment] 2016-02-11 18:15
@pdewouters Reverting to 3.4.2 also the backup of the database is truncated.
In complete backup or only database backup the database backup file only has this:
```
-- MySQL dump 10.13  Distrib 5.6.28, for Linux (x86_64)
--
-- Host: localhost    Database: XXXXXXXXXXXXXXXXXXX
-- ------------------------------------------------------
-- Server version	5.6.28

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
```

**Comment by RubenMartins** [comment] 2016-02-11 18:21
@pdewouters Now i revert to 3.4.1 also the problem is still happening.

Also update this version 3.4.1 to 3.4.3 from the plugins page normaly to check if it solves the problem but no, is still not making the backup of database correctly.

So probably is something registered in the database related with the plugin that make the plugin stop to work since i only rollback the files, didn't touch the database.

**Comment by RubenMartins** [comment] 2016-02-11 18:32
The option value "hmbkp_plugin_version" can somehow make any diference when downgrade the versions?

**Comment by pdewouters** [comment] 2016-02-12 15:17
could you share the data from the server info tab?

**Comment by RubenMartins** [comment] 2016-02-12 17:54
Sure, this is the info:

`**PHP**

ZipArchive	Yes
DirectoryIterator FOLLOW_SYMLINKS	Yes
User	*ACCOUNT*
Group[s]	*ACCOUNT*
Version	5.3.29
Safe Mode	No
Exec	Yes
Memory Limit	256M
Interface	apache2handler
Disabled Functions	No
open_basedir	No
Max execution time	No
PDO
sqlite, mysql, sqlite2
Server

zip command	zip
mysqldump command	mysqldump
**Server**
Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4 PHP/5.3.29
OS	Linux
**Site**

Cron Array	
array (
  1455299323 => 
  array (
    'w3_pgcache_cleanup' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'w3_pgcache_cleanup',
        'args' => 
        array (
        ),
        'interval' => 3600,
      ),
    ),
    'w3_objectcache_cleanup' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'w3_objectcache_cleanup',
        'args' => 
        array (
        ),
        'interval' => 3600,
      ),
    ),
  ),
  1455299408 => 
  array (
    'alo_em_batch' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'alo_em_interval',
        'args' => 
        array (
        ),
        'interval' => 295,
      ),
    ),
  ),
  1455299512 => 
  array (
    'w3_pgcache_prime' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'w3_pgcache_prime',
        'args' => 
        array (
        ),
        'interval' => 900,
      ),
    ),
  ),
  1455299585 => 
  array (
    'w3_pgcache_prime' => 
    array (
      'b4267a67df0cfb11e30d6396f858b5c9' => 
      array (
        'schedule' => false,
        'args' => 
        array (
          0 => 40,
        ),
      ),
    ),
  ),
  1455300575 => 
  array (
    'qs_cron_hook' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'hourly',
        'args' => 
        array (
        ),
        'interval' => 3600,
      ),
    ),
  ),
  1455300839 => 
  array (
    'wp_session_garbage_collection' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'twicedaily',
        'args' => 
        array (
        ),
        'interval' => 43200,
      ),
    ),
  ),
  1455302405 => 
  array (
    'w3_dbcache_cleanup' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'w3_dbcache_cleanup',
        'args' => 
        array (
        ),
        'interval' => 3600,
      ),
    ),
  ),
  1455305390 => 
  array (
    'ao_cachechecker' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'daily',
        'args' => 
        array (
        ),
        'interval' => 86400,
      ),
    ),
  ),
  1455319646 => 
  array (
    'alo_em_schedule' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'twicedaily',
        'args' => 
        array (
        ),
        'interval' => 43200,
      ),
    ),
  ),
  1455338113 => 
  array (
    'wp_version_check' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'twicedaily',
        'args' => 
        array (
        ),
        'interval' => 43200,
      ),
    ),
    'wp_update_themes' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'twicedaily',
        'args' => 
        array (
        ),
        'interval' => 43200,
      ),
    ),
  ),
  1455338902 => 
  array (
    'wp_update_plugins' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'twicedaily',
        'args' => 
        array (
        ),
        'interval' => 43200,
      ),
    ),
  ),
  1455375600 => 
  array (
    'hmbkp_schedule_hook' => 
    array (
      '887abd106b36605fbb285d0dec9f47ac' => 
      array (
        'schedule' => 'daily',
        'args' => 
        array (
          'id' => 'default-1',
        ),
        'interval' => 86400,
      ),
    ),
  ),
  1455381319 => 
  array (
    'wp_scheduled_delete' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'daily',
        'args' => 
        array (
        ),
        'interval' => 86400,
      ),
    ),
  ),
  1455382300 => 
  array (
    'wp_scheduled_auto_draft_delete' => 
    array (
      '40cd750bba9870f18aada2478b24840a' => 
      array (
        'schedule' => 'daily',
        'args' => 
        array (
        ),
        'interval' => 86400,
      ),
    ),
  ),
  1455505200 => 
  array (
    'hmbkp_schedule_hook' => 
    array (
      '61a45f8e0e711228d9f0aa04271d0a05' => 
      array (
        'schedule' => 'weekly',
        'args' => 
        array (
          'id' => 'default-2',
        ),
        'interval' => 604800,
      ),
    ),
  ),
  'version' => 2,
)
Language	pt_PT
Backup Path
/home/*ACCOUNT*/public_html/*FOLDER*/*SITE*.pt/wp-content/backupwordpress-XXXXXXXXXX-backups
Backup Path Permissions	0755
WP_CONTENT_DIR
/home/*ACCOUNT*/public_html/*FOLDER*/*SITE*.pt/wp-content
WP_CONTENT_DIR Permissions	0755
ABSPATH
/home/*ACCOUNT*/public_html/*FOLDER*/*SITE*.pt/
Site Root Path
/home/*ACCOUNT*/public_html/*FOLDER*/*SITE*.pt
Calculated size of site	
array (
)
WP Cron Test Failed	No
Active Plugins	
array (
  0 => 'acf-qtranslate/acf-qtranslate.php',
  1 => 'advanced-custom-fields/acf.php',
  2 => 'allow-multiple-accounts/allow-multiple-accounts.php',
  3 => 'alo-easymail/alo-easymail.php',
  4 => 'autoptimize/autoptimize.php',
  5 => 'backupwordpress/backupwordpress.php',
  6 => 'contact-form-7/wp-contact-form-7.php',
  7 => 'event-manager/event-manager.php',
  8 => 'ewww-image-optimizer/ewww-image-optimizer.php',
  9 => 'flamingo/flamingo.php',
  10 => 'font-awesome/plugin.php',
  11 => 'google-document-embedder/gviewer.php',
  12 => 'mqtranslate/mqtranslate.php',
  13 => 'qtranslate-extended/qtranslate-extended.php',
  14 => 'quick-and-easy-faqs/quick-and-easy-faqs.php',
  15 => 'tablepress/tablepress.php',
  16 => 'template/template.class.php',
  17 => 'tinymce-advanced/tinymce-advanced.php',
  18 => 'user-role-editor/user-role-editor.php',
  19 => 'w3-total-cache/w3-total-cache.php',
  20 => 'wordpress-seo/wp-seo.php',
  21 => 'yoast-seo-fix-for-qtranslate/Yoast SEO fix for qTranslate.php',
)
Home URL
http://www.*SITE*.pt
Site URL
http://www.*SITE*.pt
**Constants**

HMBKP_PATH	No
HMBKP_ROOT	No
HMBKP_MYSQLDUMP_PATH	No
HMBKP_ZIP_PATH	No
HMBKP_CAPABILITY	No
HMBKP_EMAIL	No
HMBKP_ATTACHMENT_MAX_FILESIZE	No
HMBKP_EXCLUDE	No
Plugin Version	3.4.3`

**Comment by willmot** [comment] 2016-02-19 15:53
what's odd here is that the database backup is using `mysqldump` via the command-line, something must be killing that process, unfortunately we don't currently have a way to detect that I don't think.

May have to wait until we implement #945

**Comment by RubenMartins** [comment] 2016-02-24 17:34
I don't know if this could help but I already talked to my hosting provider and we test the `mysqldump -u username -p dbname > dbexport.sql ` command directly from the commandline and it works just fine exporting the full database to the file.

They also asked me what is the command the plugin uses to run the mysqldump so they can test it out. I already checked the plugin files in search of the command but without luck can you help me?

PS: I already updated to the latest version 3.4.5 but the issue remains.

**Comment by pdewouters** [comment] 2016-02-24 20:34
thanks. yes that's interesting, the command is built dynamically, but I'll try and give you an example as close as possible as what it might be

**Comment by willmot** [comment] 2016-02-28 18:01
@RubenMartins could you possibly test https://github.com/humanmade/backupwordpress/issues/1001, my hope is that by switching to Process we'll now correctly catch that the command didn't finish successfully.

**Comment by willmot** [comment] 2016-02-28 18:36
Looking into this more and I think I found the issue, we weren't correctly detecting errors in the dump process and falling back, since https://github.com/humanmade/backupwordpress/commit/9dbcac6c65deba50c1171909c34e1ba886fc6286 I'm now almost certain this is going to be fixed in #1001

**Comment by RubenMartins** [comment] 2016-02-29 15:58
@willmot When activating the plugin with the commit #1001 returned me this errors
```
Warning: require_once(/wp-content/plugins/backupwordpress/vendor/autoload.php) [function.require-once]: failed to open stream: No such file or directory in /wp-content/plugins/backupwordpress/classes/class-plugin.php on line 119

Fatal error: require_once() [function.require]: Failed opening required '/wp-content/plugins/backupwordpress/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /wp-content/plugins/backupwordpress/classes/class-plugin.php on line 119
```

**Comment by willmot** [comment] 2016-02-29 16:37
@RubenMartins you need to run `composer install` from inside the plugin directory to grab those dependencies

**Comment by willmot** [comment] 2016-03-03 16:59
@katmoody this is one of the issues that should be resolved by the 3.5 beta

**Comment by willmot** [comment] 2016-03-11 22:59
Going to close this as fixed as it should be by 3.5. @katmoody let's re-open if it rears it head again.

**Closed by willmot** 2016-03-11 22:59 UTC
Labels: Bug

**Comment by RubenMartins** [comment] 2016-03-13 14:06
@willmot with your last update 3.5 i can see the error witch was related to permissions on database for Lock Tables, I gave permissions for that and now works like a charm ;)

`BackUpWordPress detected issues with your last backup.
**Mysqldump: Warning: Using a password on the command line interface can be insecure.**
mysqldump: Got error: 1044: Access denied for user 'USER_NAME'@'localhost' to database 'DATABASE_NAME' when using LOCK TABLES
IMysqldump: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'USER_NAME'@'localhost' to database 'DATABASE_NAME`

Tanks for the awesome plugin :)

**Comment by willmot** [comment] 2016-03-13 14:07
That's great, thanks for reporting back @RubenMartins 👍

**Comment by pdewouters** [comment] 2016-03-14 10:24
nice one!

**Comment by katmoody** [comment] 2016-04-04 16:14
FYI for another site experiencing issues with incomplete backups, they just reported back that updating to 3.6 completely fixed the issue for them ;-)
