### ISSUE TITLE
SSL Handshake failure

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#955] opened 2015-12-18 13:49 UTC
Based on tickets
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1560576796
and
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1555607589

Unable to connect to our server to authenticate or to download new versions of pro plugins

**Comment by katmoody** [comment] 2015-12-28 16:36
Problem is still occurring with multiple additional tickets related to this issue. (highlighted via pinned post in the Slack channel) 

This wp.org forum post appears to point to a potential solution: 
https://wordpress.org/support/topic/plugin-easy-digital-downloads-not-working-check-is-always-empty?replies=46

With more information highlighted here: 
https://easydigitaldownloads.com/forums/topic/shopping-cart-is-empty-upon-checkout/

Looks to me that if confirmed as the actual problem it will be an easy fix for someone able to work on the server. ;-)

**Comment by owaincuvelier** [comment] 2016-01-04 16:46
returned error: `error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

**Comment by owaincuvelier** [comment] 2016-01-19 14:12
So for the time being I've set the plugin update method in the EDD settings to use 'redirect' over 'force. 

This effects specifically plugin updates. I'm unsure about the authentication issue, I've been unable to reproduce it as yet.

**Comment by owaincuvelier** [comment] 2016-01-19 14:16
in addition to this, I do suspect some people will be experiencing issues from the pre 4.4.1 openssl bug.

**Comment by katmoody** [comment] 2016-01-19 19:42
So to confirm: 

1. Premium plugins can only be updated automatically if they had already had their licenses authenticated. 
2. While the premium plugins will work without authenticating, trying to authenticate will run into that error on affected servers.
3. In these cases, manually updating for the time being is the only solution.

It's not a big deal for those who just use it on theirs and another site or two ... but for folks who have it running on multiple sites that is cruddy ... darn openssl.

**Comment by willmot** [comment] 2016-01-22 14:32
> I do suspect some people will be experiencing issues from the pre 4.4.1 openssl bug.

Worth noting, this only affected people on 4.4, the bug wasn't present in early versions of WordPress

**Comment by willmot** [comment] 2016-01-22 14:41
In summary,

- Updating plugins should now have been fixed, since https://github.com/humanmade/backupwordpress/issues/955#issuecomment-172864735
- The issue with license authentication is less clear, we haven't been able to reproduce. Current best guess is that it's people who are on 4.4 and have OpenSSL `1.0.1e`. @katmoody to confirm that next time we get a report and then confirm whether updating that person to 4.4.1 fixes the issue.

**Comment by willmot** [comment] 2016-01-22 14:54
> @katmoody to confirm that next time we get a report and then confirm whether updating that person to 4.4.1 fixes the issue.

Actually doesn't seem like this is the specific issue as we have reports of people on 4.4.1 who are hitting the issue.

Next step here is to at least reproduce that the issue is specific to older versions of OpenSSL.

**Comment by willmot** [comment] 2016-02-26 17:53
@owaincuvelier @pdewouters @katmoody is this still an issue? still being worked on?

**Comment by owaincuvelier** [comment] 2016-02-26 18:33
@willmot I've got a PR open on our hm-stack that should fix this.

**Comment by willmot** [comment] 2016-02-27 10:27
@owaincuvelier cool, is that: https://github.com/humanmade/hm-salt/pull/63?

**Comment by owaincuvelier** [comment] 2016-03-02 14:53
@willmot it is. Waiting for a merge

**Comment by willmot** [comment] 2016-03-03 10:15
@owaincuvelier sweet, this fixed now that's merged?

**Comment by owaincuvelier** [comment] 2016-03-03 12:54
@willmot I've updated our stack & reached out to a user who was having the issue, just waiting for conformation.

**Closed** 2016-03-09 19:49 UTC
Labels: Bug

**Comment by willmot** [comment] 2016-03-09 19:51
Closing as @owaincuvelier mentioned in [Slack that this is now resolved](https://hmn.slack.com/archives/backupwordpress/p1457369379000185)
