### ISSUE TITLE
Character Encoding Issue Resulting in Missing Images from Backup

### ISSUE THREAD

**Issue by katmoody** [humanmade/backupwordpress#978] opened 2016-01-27 16:12 UTC
Missing picture files have special characters like `ß`, `ä`, `ü`, `ö` in their filename, and the ticket includes multiple examples as well as part of an SQL file with the proper image names. 

In Intercom: https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/1748537135

**Comment by pdewouters** [comment] 2016-01-27 16:17
I wonder if Symfony Finder is causing this issue

**Comment by katmoody** [comment] 2016-02-01 15:04
Just an update (still on the same ticket there) ... after the update last week, he now has the full backup with images, BUT the slugs have changed. From his newest message: 

```
...now the backup file contains at least all image files (before that update image files with special characters were missing in the backup file).

However, during backup the filenames of images with special characters are changed so that after restore these filenames don’t match with the stored filename/slug in the SQL DB.
```

**Comment by willmot** [comment] 2016-02-01 15:56
Seems like a perfect chance for some unit tests, we should be able to add a unit test for files with strange characters and have that run across both `zip` and `ZipArchive`.

**Comment by willmot** [comment] 2016-02-02 17:53
I haven't been able to reproduce this. I've tried two separate approaches.

- I added a unit test to cover backing a file called `Groß.jpg` in https://github.com/humanmade/backupwordpress/pull/981. This passes on both `zip` and `ZipArchive`
- I manually tested by uploading an image called `Groß.jpg`, performing a backup and then completely restoring my site from the backup, the image continued to work fine.

I'm going to test on Windows in-case this is specific to that OS.

**Comment by willmot** [comment] 2016-02-03 10:30
I wasn't able to reproduce this on Windows either. @katmoody could you point the person who contacted support at this ticket so we can continue debugging.

**Comment by katmoody** [comment] 2016-02-03 13:27
Done - will update.

**Comment by katmoody** [comment] 2016-02-04 17:14
Hey - he's updated with a test environment login for you guys - go forth and test merrily :smile:

**Comment by willmot** [comment] 2016-02-19 16:17
I've had a good look into this and am 99% certain that BackUpWordPress is correct here.

The images have special characters in the filename and those characters are handled correctly when zipping the files up. Similarly the characters are correct in the database backup.

The issue seems to be that when the user has unzipped the files and then transferred them to his server, his file transfer program WinSCP hasn't properly preserved the encoding. Have communicated as much to the original support request.

**Closed by willmot** 2016-02-19 16:17 UTC
Labels: Bug, Needs confirmation, Reporter Feedback
